//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Online.
        /// </summary>
        public static string ChatOnline {
            get {
                return ResourceManager.GetString("ChatOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name must be less than 30 and more than 1 character(s).
        /// </summary>
        public static string ClassLong {
            get {
                return ResourceManager.GetString("ClassLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class / Deparment.
        /// </summary>
        public static string ClassOrDeparment {
            get {
                return ResourceManager.GetString("ClassOrDeparment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should tell us which class / deparment belong to.
        /// </summary>
        public static string ClassRequired {
            get {
                return ResourceManager.GetString("ClassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQmgs.com - Every student of Zhejiang Gongshang University deserve it !.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name must be required.
        /// </summary>
        public static string LoginUserNameRequired {
            get {
                return ResourceManager.GetString("LoginUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Interests.
        /// </summary>
        public static string MeetInterests {
            get {
                return ResourceManager.GetString("MeetInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for ZJSU.
        /// </summary>
        public static string OnlyForZJSU {
            get {
                return ResourceManager.GetString("OnlyForZJSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should must be less than 30 and more than 4 characters.
        /// </summary>
        public static string PasswordLong {
            get {
                return ResourceManager.GetString("PasswordLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide your password.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Must be less than 50 and more than 3 characters.
        /// </summary>
        public static string UserNameLong {
            get {
                return ResourceManager.GetString("UserNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name must be required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TwitterV account to log in..
        /// </summary>
        public static string UseTwitterVAccountToLogIn {
            get {
                return ResourceManager.GetString("UseTwitterVAccountToLogIn", resourceCulture);
            }
        }
    }
}
